name: jadwal

on:
  push:
    branches:
      - "*"
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Start build job"
        run: |
          echo "Starting the build job"
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Login to Dockerhub"
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.docker_username }}"
          password: "${{ secrets.docker_token }}"

      - name: "Build and push"
        run: |
          docker build -f Docker/dockerfile/app.Dockerfile -t app .
          docker build -f Docker/dockerfile/web_server.Dockerfile -t web_server .
          docker tag app ${{ secrets.docker_username}}/jadwal
          docker tag web_server ${{ secrets.docker_username}}/jadwal-web_server
          docker push ${{ secrets.docker_username}}/jadwal
          docker push ${{ secrets.docker_username}}/jadwal-web_server
      - name: "Write config"
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.oci_user_ocid}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.oci_fingerprint}}" >> ~/.oci/config
          echo "region=${{secrets.oci_region}}" >> ~/.oci/config
          echo "tenancy=${{secrets.oci_tenancy_ocid}}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "${{secrets.oci_key_file}}" >> ~/.oci/oci_api_key.pem
          echo "${{secrets.oci_key_public}}" >> ~/.oci/oci_api_key_public.pem
      - name: "Install OCI CLI"
        run: |
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
      - name: "Fix Config File Permissions"
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/oci_api_key.pem
      - name: "Check Existing Instance"
        run: |
          echo "INSTANCE_OCID=$( \
            oci compute instance list \
            --lifecycle-state RUNNING \
            --compartment-id ${{secrets.vm_compartment_ocid}} \
            --display-name server-docker \
            --query "data [0].id" \
            --raw-output \
            )" >> $GITHUB_ENV
      - name: "Get Instance IP"
        run: |
          echo "INSTANCE_IP=$( \
            oci compute instance list-vnics \
            --instance-id ${{secrets.coi_instance_ocid}} \
            --query 'data [0]."public-ip"' \
            --raw-output \
            )" >> $GITHUB_ENV
          echo Instance IP: ${{ env.INSTANCE_IP }}
      - name: "Wait for SSH"
        run: |
          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
          sleep 5
          echo "SSH not available..."
          done; echo "SSH ready!"
      - name: "Deploy Deployment Configuration"
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.oci_instance_key }}
          source: "docker-compose.yml"
          target: "./"

      - name: "Running Docker Compose"
        uses: appleboy/ssh-action@master
        with:
          host: ${{env.INSTANCE_IP}}
          username: ubuntu
          key: ${{secrets.oci_instance_key}}
          script: |
            sudo docker pull adn13/jadwal
            sudo docker pull adn13/jadwal-web_server
            sudo docker-compose up -d
            sudo docker exec app /bin/bash -c "php artisan key:generate"
            sudo docker exec app /bin/bash -c "echo 'DB_CONNECTION=${{ secrets.db_connection }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_HOST=${{ secrets.db_host }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_PORT=${{ secrets.db_port }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_DATABASE=${{ secrets.db_database }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_USERNAME=${{ secrets.db_username }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_PASSWORD=${{ secrets.db_password }}' >> .env"
            sudo docker exec app /bin/bash -c "echo 'DB_REDIS=cache' >> .env"
            sudo docker exec app /bin/bash -c "php artisan migrate:fresh --seed"
            sudo docker exec app /bin/bash -c "php artisan storage:link"
            sudo docker exec app /bin/bash -c "php artisan jwt:secret"
